import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface Language {
  code: string;
  name: string;
  native: string;
  flag: string;
}

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (language: string) => void;
  supportedLanguages: Language[];
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

const supportedLanguages: Language[] = [
  { code: 'en', name: 'English', native: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳' }
];

const translations: Translations = {
  en: {
    // Header
    'header.title': 'DVote',
    'header.subtitle': 'Decentralized Voting System',
    'header.dashboard': 'Dashboard',
    'header.register': 'Register',
    'header.vote': 'Vote',
    'header.results': 'Results',
    'header.audit': 'Audit Trail',
    'header.admin': 'Admin',
    'header.aiSetup': 'AI Setup',
    'header.connectWallet': 'Connect MetaMask',
    'header.disconnect': 'Disconnect',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to DVote',
    'dashboard.description': 'India\'s first decentralized voting platform powered by blockchain technology. Ensuring transparent, secure, and verifiable elections for a democratic future.',
    'dashboard.connectWallet': 'Connect your MetaMask wallet to participate in voting',
    'dashboard.totalVoters': 'Total Voters',
    'dashboard.votesCast': 'Votes Cast',
    'dashboard.activeElections': 'Active Elections',
    'dashboard.turnoutRate': 'Turnout Rate',
    'dashboard.registerToVote': 'Register to Vote',
    'dashboard.castVote': 'Cast Your Vote',
    'dashboard.viewResults': 'View Results',
    'dashboard.auditTrail': 'Audit Trail',
    'dashboard.secureTransparent': 'Secure & Transparent',
    'dashboard.secureDescription': 'Blockchain-based voting ensures tamper-proof elections with complete transparency.',
    'dashboard.onePersonOneVote': 'One Person, One Vote',
    'dashboard.onePersonDescription': 'MetaMask integration ensures each wallet can only vote once per election.',
    'dashboard.realTimeResults': 'Real-time Results',
    'dashboard.realTimeDescription': 'View live voting results and comprehensive analytics as votes are cast.',
    'dashboard.auditTrailFeature': 'Audit Trail',
    'dashboard.auditDescription': 'Complete transaction history and verification for all voting activities.',
    'dashboard.voteNow': 'Vote Now',
    
    // Voter Registration
    'registration.title': 'Voter Registration',
    'registration.subtitle': 'Register to participate in decentralized voting',
    'registration.secureRegistration': 'Secure Registration',
    'registration.securityNotice': 'Your registration will be recorded on the blockchain and linked to your wallet address. This ensures one person, one vote while maintaining privacy and security.',
    'registration.fullName': 'Full Name',
    'registration.email': 'Email Address',
    'registration.phone': 'Phone Number',
    'registration.aadhaar': 'Aadhaar Number',
    'registration.address': 'Address',
    'registration.connectedWallet': 'Connected Wallet',
    'registration.walletNotice': 'Your registration will be linked to:',
    'registration.terms': 'By registering, you agree that your information will be stored on the blockchain for voting verification purposes. This registration is permanent and cannot be modified.',
    'registration.register': 'Register as Voter',
    'registration.registering': 'Registering...',
    'registration.success': 'Registration Successful!',
    'registration.successMessage': 'You have been successfully registered as a voter on the blockchain.',
    'registration.alreadyRegistered': 'Already Registered',
    'registration.alreadyMessage': 'You are already registered as a voter with this wallet address.',
    'registration.walletNotConnected': 'Wallet Not Connected',
    'registration.connectMessage': 'Please connect your MetaMask wallet to register as a voter.',
    'registration.goToVoting': 'Go to Voting Booth',
    
    // Voting Booth
    'voting.title': 'Voting Booth',
    'voting.subtitle': 'Cast your vote securely on the blockchain',
    'voting.selectElection': 'Select Election',
    'voting.selectCandidate': 'Select Candidate',
    'voting.confirmVote': 'Confirm Your Vote',
    'voting.election': 'Election:',
    'voting.selectedCandidate': 'Selected Candidate:',
    'voting.important': 'Important:',
    'voting.permanentWarning': 'Once you cast your vote, it cannot be changed. Your vote will be recorded on the blockchain and is permanent.',
    'voting.castVote': 'Cast Vote',
    'voting.castingVote': 'Casting Vote...',
    'voting.voteConfirmed': 'Vote Confirmed!',
    'voting.confirmMessage': 'Your vote has been successfully recorded on the blockchain.',
    'voting.voteAnother': 'Vote in Another Election',
    'voting.alreadyVoted': 'Already Voted',
    'voting.noActiveElections': 'No Active Elections',
    'voting.noElectionsMessage': 'There are currently no active elections available for voting.',
    
    // Results
    'results.title': 'Election Results',
    'results.subtitle': 'Real-time voting results powered by blockchain',
    'results.selectElection': 'Select Election',
    'results.totalVotes': 'Total Votes',
    'results.turnout': 'Turnout',
    'results.leading': 'Leading',
    'results.voteDistribution': 'Vote Distribution',
    'results.liveUpdates': 'Live Updates',
    'results.liveMessage': 'Results are updated in real-time as votes are cast and confirmed on the blockchain. All vote counts are verifiable through the audit trail.',
    'results.noElections': 'No Elections Available',
    'results.noElectionsMessage': 'There are currently no elections to display results for.',
    
    // Audit Trail
    'audit.title': 'Audit Trail',
    'audit.subtitle': 'Complete transparency through blockchain verification',
    'audit.search': 'Search by transaction hash or voter address...',
    'audit.allTransactions': 'All Transactions',
    'audit.votes': 'Votes',
    'audit.registrations': 'Registrations',
    'audit.elections': 'Elections',
    'audit.totalTransactions': 'Total Transactions',
    'audit.votesCast': 'Votes Cast',
    'audit.gasUsed': 'Gas Used',
    'audit.transactionHistory': 'Transaction History',
    'audit.transactionHash': 'Transaction Hash',
    'audit.type': 'Type',
    'audit.voterAddress': 'Voter Address',
    'audit.timestamp': 'Timestamp',
    'audit.status': 'Status',
    'audit.confirmed': 'Confirmed',
    'audit.noTransactions': 'No transactions found matching your criteria.',
    
    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'Manage elections and monitor system performance',
    'admin.totalElections': 'Total Elections',
    'admin.registeredVoters': 'Registered Voters',
    'admin.systemStatus': 'System Status',
    'admin.active': 'Active',
    'admin.quickActions': 'Quick Actions',
    'admin.createElection': 'Create New Election',
    'admin.manageVoters': 'Manage Voters',
    'admin.viewAnalytics': 'View Analytics',
    'admin.activeElections': 'Active Elections',
    'admin.noElections': 'No active elections. Create one to get started.',
    'admin.edit': 'Edit',
    'admin.end': 'End',
    'admin.accessDenied': 'Access Denied',
    'admin.connectWalletMessage': 'Please connect your wallet to access the admin panel.',
    'admin.unauthorized': 'Unauthorized Access',
    'admin.noPrivileges': 'You do not have administrator privileges to access this panel.',
    
    // Create Election Modal
    'createElection.title': 'Create New Election',
    'createElection.electionTitle': 'Election Title',
    'createElection.description': 'Description',
    'createElection.startTime': 'Start Time',
    'createElection.endTime': 'End Time',
    'createElection.candidates': 'Candidates',
    'createElection.addCandidate': 'Add Candidate',
    'createElection.candidateName': 'Candidate Name',
    'createElection.party': 'Party',
    'createElection.candidateDescription': 'Description',
    'createElection.create': 'Create Election',
    'createElection.cancel': 'Cancel',
    
    // Chatbot
    'chatbot.title': 'DVote Assistant',
    'chatbot.greeting': 'Hello! I\'m your DVote assistant. How can I help you with voting today?',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.languageChanged': 'Language changed to English. How can I help you with DVote?',
    'chatbot.errorMessage': 'I\'m sorry, I\'m having trouble connecting to the AI service. Please make sure Ollama is running with the deepseek-r1 model.',
    'chatbot.stopSpeaking': 'Stop speaking',
    'chatbot.readAloud': 'Read aloud',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.yes': 'Yes',
    'common.no': 'No',
  },
  
  hi: {
    // Header
    'header.title': 'डीवोट',
    'header.subtitle': 'विकेंद्रीकृत मतदान प्रणाली',
    'header.dashboard': 'डैशबोर्ड',
    'header.register': 'पंजीकरण',
    'header.vote': 'मतदान',
    'header.results': 'परिणाम',
    'header.audit': 'ऑडिट ट्रेल',
    'header.admin': 'एडमिन',
    'header.aiSetup': 'AI सेटअप',
    'header.connectWallet': 'MetaMask कनेक्ट करें',
    'header.disconnect': 'डिस्कनेक्ट',
    
    // Dashboard
    'dashboard.welcome': 'डीवोट में आपका स्वागत है',
    'dashboard.description': 'भारत का पहला विकेंद्रीकृत मतदान प्लेटफॉर्म जो ब्लॉकचेन तकनीक द्वारा संचालित है। लोकतांत्रिक भविष्य के लिए पारदर्शी, सुरक्षित और सत्यापन योग्य चुनाव सुनिश्चित करता है।',
    'dashboard.connectWallet': 'मतदान में भाग लेने के लिए अपना MetaMask वॉलेट कनेक्ट करें',
    'dashboard.totalVoters': 'कुल मतदाता',
    'dashboard.votesCast': 'डाले गए वोट',
    'dashboard.activeElections': 'सक्रिय चुनाव',
    'dashboard.turnoutRate': 'मतदान दर',
    'dashboard.registerToVote': 'मतदान के लिए पंजीकरण',
    'dashboard.castVote': 'अपना वोट डालें',
    'dashboard.viewResults': 'परिणाम देखें',
    'dashboard.auditTrail': 'ऑडिट ट्रेल',
    'dashboard.secureTransparent': 'सुरक्षित और पारदर्शी',
    'dashboard.secureDescription': 'ब्लॉकचेन-आधारित मतदान पूर्ण पारदर्शिता के साथ छेड़छाड़-रोधी चुनाव सुनिश्चित करता है।',
    'dashboard.onePersonOneVote': 'एक व्यक्ति, एक वोट',
    'dashboard.onePersonDescription': 'MetaMask एकीकरण सुनिश्चित करता है कि प्रत्येक वॉलेट प्रति चुनाव केवल एक बार वोट कर सकता है।',
    'dashboard.realTimeResults': 'रियल-टाइम परिणाम',
    'dashboard.realTimeDescription': 'वोट डाले जाने पर लाइव मतदान परिणाम और व्यापक विश्लेषण देखें।',
    'dashboard.auditTrailFeature': 'ऑडिट ट्रेल',
    'dashboard.auditDescription': 'सभी मतदान गतिविधियों के लिए पूर्ण लेनदेन इतिहास और सत्यापन।',
    'dashboard.voteNow': 'अभी वोट करें',
    
    // Voter Registration
    'registration.title': 'मतदाता पंजीकरण',
    'registration.subtitle': 'विकेंद्रीकृत मतदान में भाग लेने के लिए पंजीकरण करें',
    'registration.secureRegistration': 'सुरक्षित पंजीकरण',
    'registration.securityNotice': 'आपका पंजीकरण ब्लॉकचेन पर रिकॉर्ड किया जाएगा और आपके वॉलेट पते से जुड़ा होगा। यह गोपनीयता और सुरक्षा बनाए रखते हुए एक व्यक्ति, एक वोट सुनिश्चित करता है।',
    'registration.fullName': 'पूरा नाम',
    'registration.email': 'ईमेल पता',
    'registration.phone': 'फोन नंबर',
    'registration.aadhaar': 'आधार नंबर',
    'registration.address': 'पता',
    'registration.connectedWallet': 'कनेक्टेड वॉलेट',
    'registration.walletNotice': 'आपका पंजीकरण इससे जुड़ा होगा:',
    'registration.terms': 'पंजीकरण करके, आप सहमत हैं कि आपकी जानकारी मतदान सत्यापन उद्देश्यों के लिए ब्लॉकचेन पर संग्रहीत की जाएगी। यह पंजीकरण स्थायी है और इसे संशोधित नहीं किया जा सकता।',
    'registration.register': 'मतदाता के रूप में पंजीकरण करें',
    'registration.registering': 'पंजीकरण हो रहा है...',
    'registration.success': 'पंजीकरण सफल!',
    'registration.successMessage': 'आप ब्लॉकचेन पर मतदाता के रूप में सफलतापूर्वक पंजीकृत हो गए हैं।',
    'registration.alreadyRegistered': 'पहले से पंजीकृत',
    'registration.alreadyMessage': 'आप इस वॉलेट पते के साथ पहले से ही मतदाता के रूप में पंजीकृत हैं।',
    'registration.walletNotConnected': 'वॉलेट कनेक्ट नहीं है',
    'registration.connectMessage': 'मतदाता के रूप में पंजीकरण करने के लिए कृपया अपना MetaMask वॉलेट कनेक्ट करें।',
    'registration.goToVoting': 'मतदान बूथ पर जाएं',
    
    // Voting Booth
    'voting.title': 'मतदान बूथ',
    'voting.subtitle': 'ब्लॉकचेन पर सुरक्षित रूप से अपना वोट डालें',
    'voting.selectElection': 'चुनाव चुनें',
    'voting.selectCandidate': 'उम्मीदवार चुनें',
    'voting.confirmVote': 'अपने वोट की पुष्टि करें',
    'voting.election': 'चुनाव:',
    'voting.selectedCandidate': 'चयनित उम्मीदवार:',
    'voting.important': 'महत्वपूर्ण:',
    'voting.permanentWarning': 'एक बार आपका वोट डालने के बाद, इसे बदला नहीं जा सकता। आपका वोट ब्लॉकचेन पर रिकॉर्ड किया जाएगा और स्थायी है।',
    'voting.castVote': 'वोट डालें',
    'voting.castingVote': 'वोट डाला जा रहा है...',
    'voting.voteConfirmed': 'वोट की पुष्टि हो गई!',
    'voting.confirmMessage': 'आपका वोट ब्लॉकचेन पर सफलतापूर्वक रिकॉर्ड किया गया है।',
    'voting.voteAnother': 'दूसरे चुनाव में वोट करें',
    'voting.alreadyVoted': 'पहले से वोट किया गया',
    'voting.noActiveElections': 'कोई सक्रिय चुनाव नहीं',
    'voting.noElectionsMessage': 'वर्तमान में मतदान के लिए कोई सक्रिय चुनाव उपलब्ध नहीं है।',
    
    // Results
    'results.title': 'चुनाव परिणाम',
    'results.subtitle': 'ब्लॉकचेन द्वारा संचालित रियल-टाइम मतदान परिणाम',
    'results.selectElection': 'चुनाव चुनें',
    'results.totalVotes': 'कुल वोट',
    'results.turnout': 'मतदान',
    'results.leading': 'अग्रणी',
    'results.voteDistribution': 'वोट वितरण',
    'results.liveUpdates': 'लाइव अपडेट',
    'results.liveMessage': 'परिणाम रियल-टाइम में अपडेट होते हैं जैसे ही वोट डाले जाते हैं और ब्लॉकचेन पर पुष्टि होती है। सभी वोट गिनती ऑडिट ट्रेल के माध्यम से सत्यापन योग्य है।',
    'results.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'results.noElectionsMessage': 'वर्तमान में परिणाम प्रदर्शित करने के लिए कोई चुनाव नहीं है।',
    
    // Audit Trail
    'audit.title': 'ऑडिट ट्रेल',
    'audit.subtitle': 'ब्लॉकचेन सत्यापन के माध्यम से पूर्ण पारदर्शिता',
    'audit.search': 'लेनदेन हैश या मतदाता पते से खोजें...',
    'audit.allTransactions': 'सभी लेनदेन',
    'audit.votes': 'वोट',
    'audit.registrations': 'पंजीकरण',
    'audit.elections': 'चुनाव',
    'audit.totalTransactions': 'कुल लेनदेन',
    'audit.votesCast': 'डाले गए वोट',
    'audit.gasUsed': 'उपयोग की गई गैस',
    'audit.transactionHistory': 'लेनदेन इतिहास',
    'audit.transactionHash': 'लेनदेन हैश',
    'audit.type': 'प्रकार',
    'audit.voterAddress': 'मतदाता पता',
    'audit.timestamp': 'समय चिह्न',
    'audit.status': 'स्थिति',
    'audit.confirmed': 'पुष्ट',
    'audit.noTransactions': 'आपके मानदंडों से मेल खाने वाला कोई लेनदेन नहीं मिला।',
    
    // Admin Panel
    'admin.title': 'एडमिन पैनल',
    'admin.subtitle': 'चुनावों का प्रबंधन करें और सिस्टम प्रदर्शन की निगरानी करें',
    'admin.totalElections': 'कुल चुनाव',
    'admin.registeredVoters': 'पंजीकृत मतदाता',
    'admin.systemStatus': 'सिस्टम स्थिति',
    'admin.active': 'सक्रिय',
    'admin.quickActions': 'त्वरित कार्य',
    'admin.createElection': 'नया चुनाव बनाएं',
    'admin.manageVoters': 'मतदाताओं का प्रबंधन',
    'admin.viewAnalytics': 'विश्लेषण देखें',
    'admin.activeElections': 'सक्रिय चुनाव',
    'admin.noElections': 'कोई सक्रिय चुनाव नहीं। शुरू करने के लिए एक बनाएं।',
    'admin.edit': 'संपादित करें',
    'admin.end': 'समाप्त करें',
    'admin.accessDenied': 'पहुंच अस्वीकृत',
    'admin.connectWalletMessage': 'एडमिन पैनल तक पहुंचने के लिए कृपया अपना वॉलेट कनेक्ट करें।',
    'admin.unauthorized': 'अनधिकृत पहुंच',
    'admin.noPrivileges': 'आपके पास इस पैनल तक पहुंचने के लिए प्रशासक विशेषाधिकार नहीं हैं।',
    
    // Create Election Modal
    'createElection.title': 'नया चुनाव बनाएं',
    'createElection.electionTitle': 'चुनाव शीर्षक',
    'createElection.description': 'विवरण',
    'createElection.startTime': 'प्रारंभ समय',
    'createElection.endTime': 'समाप्ति समय',
    'createElection.candidates': 'उम्मीदवार',
    'createElection.addCandidate': 'उम्मीदवार जोड़ें',
    'createElection.candidateName': 'उम्मीदवार का नाम',
    'createElection.party': 'पार्टी',
    'createElection.candidateDescription': 'विवरण',
    'createElection.create': 'चुनाव बनाएं',
    'createElection.cancel': 'रद्द करें',
    
    // Chatbot
    'chatbot.title': 'डीवोट सहायक',
    'chatbot.greeting': 'नमस्ते! मैं आपका डीवोट सहायक हूं। आज मैं मतदान में आपकी कैसे सहायता कर सकता हूं?',
    'chatbot.placeholder': 'अपना संदेश टाइप करें...',
    'chatbot.languageChanged': 'भाषा हिंदी में बदल दी गई है। मैं डीवोट के साथ आपकी कैसे सहायता कर सकता हूं?',
    'chatbot.errorMessage': 'क्षमा करें, मुझे AI सेवा से जुड़ने में समस्या हो रही है। कृपया सुनिश्चित करें कि Ollama deepseek-r1 मॉडल के साथ चल रहा है।',
    'chatbot.stopSpeaking': 'बोलना बंद करें',
    'chatbot.readAloud': 'जोर से पढ़ें',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.close': 'बंद करें',
    'common.save': 'सहेजें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.required': 'आवश्यक',
    'common.optional': 'वैकल्पिक',
    'common.yes': 'हां',
    'common.no': 'नहीं',
  },
  
  ta: {
    // Header
    'header.title': 'டிவோட்',
    'header.subtitle': 'பரவலாக்கப்பட்ட வாக்களிப்பு அமைப்பு',
    'header.dashboard': 'டாஷ்போர்டு',
    'header.register': 'பதிவு',
    'header.vote': 'வாக்களிப்பு',
    'header.results': 'முடிவுகள்',
    'header.audit': 'தணிக்கை பாதை',
    'header.admin': 'நிர்வாகம்',
    'header.aiSetup': 'AI அமைப்பு',
    'header.connectWallet': 'MetaMask இணைக்கவும்',
    'header.disconnect': 'துண்டிக்கவும்',
    
    // Dashboard
    'dashboard.welcome': 'டிவோட்டிற்கு வரவேற்கிறோம்',
    'dashboard.description': 'பிளாக்செயின் தொழில்நுட்பத்தால் இயக்கப்படும் இந்தியாவின் முதல் பரவலாக்கப்பட்ட வாக்களிப்பு தளம். ஜனநாயக எதிர்காலத்திற்கான வெளிப்படையான, பாதுகாப்பான மற்றும் சரிபார்க்கக்கூடிய தேர்தல்களை உறுதி செய்கிறது.',
    'dashboard.connectWallet': 'வாக்களிப்பில் பங்கேற்க உங்கள் MetaMask வாலட்டை இணைக்கவும்',
    'dashboard.totalVoters': 'மொத்த வாக்காளர்கள்',
    'dashboard.votesCast': 'அளிக்கப்பட்ட வாக்குகள்',
    'dashboard.activeElections': 'செயலில் உள்ள தேர்தல்கள்',
    'dashboard.turnoutRate': 'வாக்களிப்பு விகிதம்',
    'dashboard.registerToVote': 'வாக்களிக்க பதிவு செய்யுங்கள்',
    'dashboard.castVote': 'உங்கள் வாக்கை அளியுங்கள்',
    'dashboard.viewResults': 'முடிவுகளைப் பார்க்கவும்',
    'dashboard.auditTrail': 'தணிக்கை பாதை',
    'dashboard.secureTransparent': 'பாதுகாப்பான மற்றும் வெளிப்படையான',
    'dashboard.secureDescription': 'பிளாக்செயின் அடிப்படையிலான வாக்களிப்பு முழு வெளிப்படைத்தன்மையுடன் சேதமடையாத தேர்தல்களை உறுதி செய்கிறது.',
    'dashboard.onePersonOneVote': 'ஒரு நபர், ஒரு வாக்கு',
    'dashboard.onePersonDescription': 'MetaMask ஒருங்கிணைப்பு ஒவ்வொரு வாலட்டும் ஒரு தேர்தலுக்கு ஒரு முறை மட்டுமே வாக்களிக்க முடியும் என்பதை உறுதி செய்கிறது.',
    'dashboard.realTimeResults': 'நிகழ்நேர முடிவுகள்',
    'dashboard.realTimeDescription': 'வாக்குகள் அளிக்கப்படும்போது நேரடி வாக்களிப்பு முடிவுகள் மற்றும் விரிவான பகுப்பாய்வுகளைப் பார்க்கவும்.',
    'dashboard.auditTrailFeature': 'தணிக்கை பாதை',
    'dashboard.auditDescription': 'அனைத்து வாக்களிப்பு நடவடிக்கைகளுக்கான முழுமையான பரிவர்த்தனை வரலாறு மற்றும் சரிபார்ப்பு.',
    'dashboard.voteNow': 'இப்போது வாக்களியுங்கள்',
    
    // Voter Registration
    'registration.title': 'வாக்காளர் பதிவு',
    'registration.subtitle': 'பரவலாக்கப்பட்ட வாக்களிப்பில் பங்கேற்க பதிவு செய்யுங்கள்',
    'registration.secureRegistration': 'பாதுகாப்பான பதிவு',
    'registration.securityNotice': 'உங்கள் பதிவு பிளாக்செயினில் பதிவு செய்யப்பட்டு உங்கள் வாலட் முகவரியுடன் இணைக்கப்படும். இது தனியுரிமை மற்றும் பாதுகாப்பை பராமரிக்கும் போது ஒரு நபர், ஒரு வாக்கை உறுதி செய்கிறது.',
    'registration.fullName': 'முழு பெயர்',
    'registration.email': 'மின்னஞ்சல் முகவரி',
    'registration.phone': 'தொலைபேசி எண்',
    'registration.aadhaar': 'ஆதார் எண்',
    'registration.address': 'முகவரி',
    'registration.connectedWallet': 'இணைக்கப்பட்ட வாலட்',
    'registration.walletNotice': 'உங்கள் பதிவு இதனுடன் இணைக்கப்படும்:',
    'registration.terms': 'பதிவு செய்வதன் மூலம், வாக்களிப்பு சரிபார்ப்பு நோக்கங்களுக்காக உங்கள் தகவல் பிளாக்செயினில் சேமிக்கப்படும் என்பதை ஒப்புக்கொள்கிறீர்கள். இந்த பதிவு நிரந்தரமானது மற்றும் மாற்ற முடியாது.',
    'registration.register': 'வாக்காளராக பதிவு செய்யுங்கள்',
    'registration.registering': 'பதிவு செய்யப்படுகிறது...',
    'registration.success': 'பதிவு வெற்றிகரமாக!',
    'registration.successMessage': 'நீங்கள் பிளாக்செயினில் வாக்காளராக வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளீர்கள்.',
    'registration.alreadyRegistered': 'ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது',
    'registration.alreadyMessage': 'இந்த வாலட் முகவரியுடன் நீங்கள் ஏற்கனவே வாக்காளராக பதிவு செய்யப்பட்டுள்ளீர்கள்.',
    'registration.walletNotConnected': 'வாலட் இணைக்கப்படவில்லை',
    'registration.connectMessage': 'வாக்காளராக பதிவு செய்ய உங்கள் MetaMask வாலட்டை இணைக்கவும்.',
    'registration.goToVoting': 'வாக்களிப்பு சாவடிக்கு செல்லுங்கள்',
    
    // Voting Booth
    'voting.title': 'வாக்களிப்பு சாவடி',
    'voting.subtitle': 'பிளாக்செயினில் பாதுகாப்பாக உங்கள் வாக்கை அளியுங்கள்',
    'voting.selectElection': 'தேர்தலைத் தேர்ந்தெடுக்கவும்',
    'voting.selectCandidate': 'வேட்பாளரைத் தேர்ந்தெடுக்கவும்',
    'voting.confirmVote': 'உங்கள் வாக்கை உறுதிப்படுத்தவும்',
    'voting.election': 'தேர்தல்:',
    'voting.selectedCandidate': 'தேர்ந்தெடுக்கப்பட்ட வேட்பாளர்:',
    'voting.important': 'முக்கியம்:',
    'voting.permanentWarning': 'ஒருமுறை உங்கள் வாக்கை அளித்தால், அதை மாற்ற முடியாது. உங்கள் வாக்கு பிளாக்செயினில் பதிவு செய்யப்பட்டு நிரந்தரமானது.',
    'voting.castVote': 'வாக்களியுங்கள்',
    'voting.castingVote': 'வாக்களிக்கப்படுகிறது...',
    'voting.voteConfirmed': 'வாக்கு உறுதிப்படுத்தப்பட்டது!',
    'voting.confirmMessage': 'உங்கள் வாக்கு பிளாக்செயினில் வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளது.',
    'voting.voteAnother': 'மற்றொரு தேர்தலில் வாக்களியுங்கள்',
    'voting.alreadyVoted': 'ஏற்கனவே வாக்களித்துள்ளீர்கள்',
    'voting.noActiveElections': 'செயலில் உள்ள தேர்தல்கள் இல்லை',
    'voting.noElectionsMessage': 'தற்போது வாக்களிப்பிற்கு செயலில் உள்ள தேர்தல்கள் எதுவும் இல்லை.',
    
    // Results
    'results.title': 'தேர்தல் முடிவுகள்',
    'results.subtitle': 'பிளாக்செயின் மூலம் இயக்கப்படும் நிகழ்நேர வாக்களிப்பு முடிவுகள்',
    'results.selectElection': 'தேர்தலைத் தேர்ந்தெடுக்கவும்',
    'results.totalVotes': 'மொத்த வாக்குகள்',
    'results.turnout': 'வாக்களிப்பு',
    'results.leading': 'முன்னணியில்',
    'results.voteDistribution': 'வாக்கு விநியோகம்',
    'results.liveUpdates': 'நேரடி புதுப்பிப்புகள்',
    'results.liveMessage': 'வாக்குகள் அளிக்கப்பட்டு பிளாக்செயினில் உறுதிப்படுத்தப்படும்போது முடிவுகள் நிகழ்நேரத்தில் புதுப்பிக்கப்படுகின்றன. அனைத்து வாக்கு எண்ணிக்கைகளும் தணிக்கை பாதை மூலம் சரிபார்க்கக்கூடியவை.',
    'results.noElections': 'தேர்தல்கள் இல்லை',
    'results.noElectionsMessage': 'தற்போது முடிவுகளைக் காட்ட தேர்தல்கள் எதுவும் இல்லை.',
    
    // Audit Trail
    'audit.title': 'தணிக்கை பாதை',
    'audit.subtitle': 'பிளாக்செயின் சரிபார்ப்பு மூலம் முழுமையான வெளிப்படைத்தன்மை',
    'audit.search': 'பரிவர்த்தனை ஹாஷ் அல்லது வாக்காளர் முகவரி மூலம் தேடுங்கள்...',
    'audit.allTransactions': 'அனைத்து பரிவர்த்தனைகள்',
    'audit.votes': 'வாக்குகள்',
    'audit.registrations': 'பதிவுகள்',
    'audit.elections': 'தேர்தல்கள்',
    'audit.totalTransactions': 'மொத்த பரிவர்த்தனைகள்',
    'audit.votesCast': 'அளிக்கப்பட்ட வாக்குகள்',
    'audit.gasUsed': 'பயன்படுத்தப்பட்ட எரிவாயு',
    'audit.transactionHistory': 'பரிவர்த்தனை வரலாறு',
    'audit.transactionHash': 'பரிவர்த்தனை ஹாஷ்',
    'audit.type': 'வகை',
    'audit.voterAddress': 'வாக்காளர் முகவரி',
    'audit.timestamp': 'நேர முத்திரை',
    'audit.status': 'நிலை',
    'audit.confirmed': 'உறுதிப்படுத்தப்பட்டது',
    'audit.noTransactions': 'உங்கள் அளவுகோல்களுடன் பொருந்தும் பரிவர்த்தனைகள் எதுவும் கிடைக்கவில்லை.',
    
    // Admin Panel
    'admin.title': 'நிர்வாக பலகம்',
    'admin.subtitle': 'தேர்தல்களை நிர்வகிக்கவும் மற்றும் கணினி செயல்திறனைக் கண்காணிக்கவும்',
    'admin.totalElections': 'மொத்த தேர்தல்கள்',
    'admin.registeredVoters': 'பதிவு செய்யப்பட்ட வாக்காளர்கள்',
    'admin.systemStatus': 'கணினி நிலை',
    'admin.active': 'செயலில்',
    'admin.quickActions': 'விரைவு நடவடிக்கைகள்',
    'admin.createElection': 'புதிய தேர்தலை உருவாக்கவும்',
    'admin.manageVoters': 'வாக்காளர்களை நிர்வகிக்கவும்',
    'admin.viewAnalytics': 'பகுப்பாய்வுகளைப் பார்க்கவும்',
    'admin.activeElections': 'செயலில் உள்ள தேர்தல்கள்',
    'admin.noElections': 'செயலில் உள்ள தேர்தல்கள் இல்லை. தொடங்க ஒன்றை உருவாக்கவும்.',
    'admin.edit': 'திருத்தவும்',
    'admin.end': 'முடிக்கவும்',
    'admin.accessDenied': 'அணுகல் மறுக்கப்பட்டது',
    'admin.connectWalletMessage': 'நிர்வாக பலகத்தை அணுக உங்கள் வாலட்டை இணைக்கவும்.',
    'admin.unauthorized': 'அங்கீகரிக்கப்படாத அணுகல்',
    'admin.noPrivileges': 'இந்த பலகத்தை அணுக உங்களுக்கு நிர்வாகி சலுகைகள் இல்லை.',
    
    // Create Election Modal
    'createElection.title': 'புதிய தேர்தலை உருவாக்கவும்',
    'createElection.electionTitle': 'தேர்தல் தலைப்பு',
    'createElection.description': 'விளக்கம்',
    'createElection.startTime': 'தொடக்க நேரம்',
    'createElection.endTime': 'முடிவு நேரம்',
    'createElection.candidates': 'வேட்பாளர்கள்',
    'createElection.addCandidate': 'வேட்பாளரைச் சேர்க்கவும்',
    'createElection.candidateName': 'வேட்பாளர் பெயர்',
    'createElection.party': 'கட்சி',
    'createElection.candidateDescription': 'விளக்கம்',
    'createElection.create': 'தேர்தலை உருவாக்கவும்',
    'createElection.cancel': 'ரத்து செய்யவும்',
    
    // Chatbot
    'chatbot.title': 'டிவோட் உதவியாளர்',
    'chatbot.greeting': 'வணக்கம்! நான் உங்கள் டிவோட் உதவியாளர். இன்று வாக்களிப்பில் நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    'chatbot.placeholder': 'உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்...',
    'chatbot.languageChanged': 'மொழி தமிழுக்கு மாற்றப்பட்டது. டிவோட் உடன் நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    'chatbot.errorMessage': 'மன்னிக்கவும், AI சேவையுடன் இணைப்பதில் சிக்கல் உள்ளது. Ollama deepseek-r1 மாதிரியுடன் இயங்குகிறது என்பதை உறுதிப்படுத்தவும்.',
    'chatbot.stopSpeaking': 'பேசுவதை நிறுத்தவும்',
    'chatbot.readAloud': 'சத்தமாக படிக்கவும்',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.cancel': 'ரத்து செய்யவும்',
    'common.confirm': 'உறுதிப்படுத்தவும்',
    'common.close': 'மூடவும்',
    'common.save': 'சேமிக்கவும்',
    'common.delete': 'நீக்கவும்',
    'common.edit': 'திருத்தவும்',
    'common.view': 'பார்க்கவும்',
    'common.required': 'தேவையான',
    'common.optional': 'விருப்பமான',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
  },
  
  te: {
    // Header
    'header.title': 'డివోట్',
    'header.subtitle': 'వికేంద్రీకృత ఓటింగ్ సిస్టమ్',
    'header.dashboard': 'డాష్‌బోర్డ్',
    'header.register': 'నమోదు',
    'header.vote': 'ఓటు',
    'header.results': 'ఫలితాలు',
    'header.audit': 'ఆడిట్ ట్రైల్',
    'header.admin': 'అడ్మిన్',
    'header.aiSetup': 'AI సెటప్',
    'header.connectWallet': 'MetaMask కనెక్ట్ చేయండి',
    'header.disconnect': 'డిస్‌కనెక్ట్',
    
    // Dashboard
    'dashboard.welcome': 'డివోట్‌కు స్వాగతం',
    'dashboard.description': 'బ్లాక్‌చెయిన్ టెక్నాలజీతో నడిచే భారతదేశం యొక్క మొదటి వికేంద్రీకృత ఓటింగ్ ప్లాట్‌ఫారమ్. ప్రజాస్వామ్య భవిష్యత్తు కోసం పారదర్శక, సురక్షిత మరియు ధృవీకరించదగిన ఎన్నికలను నిర్ధారిస్తుంది.',
    'dashboard.connectWallet': 'ఓటింగ్‌లో పాల్గొనడానికి మీ MetaMask వాలెట్‌ను కనెక్ట్ చేయండి',
    'dashboard.totalVoters': 'మొత్తం ఓటర్లు',
    'dashboard.votesCast': 'వేసిన ఓట్లు',
    'dashboard.activeElections': 'క్రియాశీల ఎన్నికలు',
    'dashboard.turnoutRate': 'ఓటింగ్ రేటు',
    'dashboard.registerToVote': 'ఓటు వేయడానికి నమోదు చేసుకోండి',
    'dashboard.castVote': 'మీ ఓటు వేయండి',
    'dashboard.viewResults': 'ఫలితాలను చూడండి',
    'dashboard.auditTrail': 'ఆడిట్ ట్రైల్',
    'dashboard.secureTransparent': 'సురక్షిత మరియు పారదర్శక',
    'dashboard.secureDescription': 'బ్లాక్‌చెయిన్ ఆధారిత ఓటింగ్ పూర్తి పారదర్శకతతో తారుమారు లేని ఎన్నికలను నిర్ధారిస్తుంది.',
    'dashboard.onePersonOneVote': 'ఒక వ్యక్తి, ఒక ఓటు',
    'dashboard.onePersonDescription': 'MetaMask ఇంటిగ్రేషన్ ప్రతి వాలెట్ ఒక ఎన్నికకు ఒకసారి మాత్రమే ఓటు వేయగలదని నిర్ధారిస్తుంది.',
    'dashboard.realTimeResults': 'రియల్ టైమ్ ఫలితాలు',
    'dashboard.realTimeDescription': 'ఓట్లు వేయబడినప్పుడు లైవ్ ఓటింగ్ ఫలితాలు మరియు సమగ్ర విశ్లేషణలను చూడండి.',
    'dashboard.auditTrailFeature': 'ఆడిట్ ట్రైల్',
    'dashboard.auditDescription': 'అన్ని ఓటింగ్ కార్యకలాపాలకు పూర్తి లావాదేవీ చరిత్ర మరియు ధృవీకరణ.',
    'dashboard.voteNow': 'ఇప్పుడే ఓటు వేయండి',
    
    // Voter Registration
    'registration.title': 'ఓటర్ నమోదు',
    'registration.subtitle': 'వికేంద్రీకృత ఓటింగ్‌లో పాల్గొనడానికి నమోదు చేసుకోండి',
    'registration.secureRegistration': 'సురక్షిత నమోదు',
    'registration.securityNotice': 'మీ నమోదు బ్లాక్‌చెయిన్‌లో రికార్డ్ చేయబడుతుంది మరియు మీ వాలెట్ చిరునామాతో లింక్ చేయబడుతుంది. ఇది గోప్యత మరియు భద్రతను కొనసాగిస్తూ ఒక వ్యక్తి, ఒక ఓటును నిర్ధారిస్తుంది.',
    'registration.fullName': 'పూర్తి పేరు',
    'registration.email': 'ఇమెయిల్ చిరునామా',
    'registration.phone': 'ఫోన్ నంబర్',
    'registration.aadhaar': 'ఆధార్ నంబర్',
    'registration.address': 'చిరునామా',
    'registration.connectedWallet': 'కనెక్ట్ చేయబడిన వాలెట్',
    'registration.walletNotice': 'మీ నమోదు దీనితో లింక్ చేయబడుతుంది:',
    'registration.terms': 'నమోదు చేయడం ద్వారా, ఓటింగ్ ధృవీకరణ ప్రయోజనాల కోసం మీ సమాచారం బ్లాక్‌చెయిన్‌లో నిల్వ చేయబడుతుందని మీరు అంగీకరిస్తున్నారు. ఈ నమోదు శాశ్వతమైనది మరియు సవరించబడదు.',
    'registration.register': 'ఓటర్‌గా నమోదు చేసుకోండి',
    'registration.registering': 'నమోదు చేస్తున్నాం...',
    'registration.success': 'నమోదు విజయవంతం!',
    'registration.successMessage': 'మీరు బ్లాక్‌చెయిన్‌లో ఓటర్‌గా విజయవంతంగా నమోదు చేసుకున్నారు.',
    'registration.alreadyRegistered': 'ఇప్పటికే నమోదు చేసుకున్నారు',
    'registration.alreadyMessage': 'మీరు ఈ వాలెట్ చిరునామాతో ఇప్పటికే ఓటర్‌గా నమోదు చేసుకున్నారు.',
    'registration.walletNotConnected': 'వాలెట్ కనెక్ట్ చేయబడలేదు',
    'registration.connectMessage': 'ఓటర్‌గా నమోదు చేసుకోవడానికి దయచేసి మీ MetaMask వాలెట్‌ను కనెక్ట్ చేయండి.',
    'registration.goToVoting': 'ఓటింగ్ బూత్‌కు వెళ్లండి',
    
    // Voting Booth
    'voting.title': 'ఓటింగ్ బూత్',
    'voting.subtitle': 'బ్లాక్‌చెయిన్‌లో సురక్షితంగా మీ ఓటు వేయండి',
    'voting.selectElection': 'ఎన్నికను ఎంచుకోండి',
    'voting.selectCandidate': 'అభ్యర్థిని ఎంచుకోండి',
    'voting.confirmVote': 'మీ ఓటును ధృవీకరించండి',
    'voting.election': 'ఎన్నిక:',
    'voting.selectedCandidate': 'ఎంచుకున్న అభ్యర్థి:',
    'voting.important': 'ముఖ్యమైనది:',
    'voting.permanentWarning': 'ఒకసారి మీ ఓటు వేసిన తర్వాత, దానిని మార్చలేరు. మీ ఓటు బ్లాక్‌చెయిన్‌లో రికార్డ్ చేయబడుతుంది మరియు శాశ్వతమైనది.',
    'voting.castVote': 'ఓటు వేయండి',
    'voting.castingVote': 'ఓటు వేస్తున్నాం...',
    'voting.voteConfirmed': 'ఓటు ధృవీకరించబడింది!',
    'voting.confirmMessage': 'మీ ఓటు బ్లాక్‌చెయిన్‌లో విజయవంతంగా రికార్డ్ చేయబడింది.',
    'voting.voteAnother': 'మరొక ఎన్నికలో ఓటు వేయండి',
    'voting.alreadyVoted': 'ఇప్పటికే ఓటు వేశారు',
    'voting.noActiveElections': 'క్రియాశీల ఎన్నికలు లేవు',
    'voting.noElectionsMessage': 'ప్రస్తుతం ఓటింగ్ కోసం క్రియాశీల ఎన్నికలు లేవు.',
    
    // Results
    'results.title': 'ఎన్నికల ఫలితాలు',
    'results.subtitle': 'బ్లాక్‌చెయిన్ ద్వారా నడిచే రియల్ టైమ్ ఓటింగ్ ఫలితాలు',
    'results.selectElection': 'ఎన్నికను ఎంచుకోండి',
    'results.totalVotes': 'మొత్తం ఓట్లు',
    'results.turnout': 'ఓటింగ్',
    'results.leading': 'ముందంజలో',
    'results.voteDistribution': 'ఓటు పంపిణీ',
    'results.liveUpdates': 'లైవ్ అప్‌డేట్‌లు',
    'results.liveMessage': 'ఓట్లు వేయబడి బ్లాక్‌చెయిన్‌లో ధృవీకరించబడినప్పుడు ఫలితాలు రియల్ టైమ్‌లో అప్‌డేట్ చేయబడతాయి. అన్ని ఓటు గణనలు ఆడిట్ ట్రైల్ ద్వారా ధృవీకరించదగినవి.',
    'results.noElections': 'ఎన్నికలు లేవు',
    'results.noElectionsMessage': 'ప్రస్తుతం ఫలితాలను చూపించడానికి ఎన్నికలు లేవు.',
    
    // Audit Trail
    'audit.title': 'ఆడిట్ ట్రైల్',
    'audit.subtitle': 'బ్లాక్‌చెయిన్ ధృవీకరణ ద్వారా పూర్తి పారదర్శకత',
    'audit.search': 'లావాదేవీ హాష్ లేదా ఓటర్ చిరునామా ద్వారా వెతకండి...',
    'audit.allTransactions': 'అన్ని లావాదేవీలు',
    'audit.votes': 'ఓట్లు',
    'audit.registrations': 'నమోదులు',
    'audit.elections': 'ఎన్నికలు',
    'audit.totalTransactions': 'మొత్తం లావాదేవీలు',
    'audit.votesCast': 'వేసిన ఓట్లు',
    'audit.gasUsed': 'ఉపయోగించిన గ్యాస్',
    'audit.transactionHistory': 'లావాదేవీ చరిత్ర',
    'audit.transactionHash': 'లావాదేవీ హాష్',
    'audit.type': 'రకం',
    'audit.voterAddress': 'ఓటర్ చిరునామా',
    'audit.timestamp': 'టైమ్‌స్టాంప్',
    'audit.status': 'స్థితి',
    'audit.confirmed': 'ధృవీకరించబడింది',
    'audit.noTransactions': 'మీ ప్రమాణాలకు సరిపోలే లావాదేవీలు కనుగొనబడలేదు.',
    
    // Admin Panel
    'admin.title': 'అడ్మిన్ ప్యానెల్',
    'admin.subtitle': 'ఎన్నికలను నిర్వహించండి మరియు సిస్టమ్ పనితీరును పర్యవేక్షించండి',
    'admin.totalElections': 'మొత్తం ఎన్నికలు',
    'admin.registeredVoters': 'నమోదైన ఓటర్లు',
    'admin.systemStatus': 'సిస్టమ్ స్థితి',
    'admin.active': 'క్రియాశీలం',
    'admin.quickActions': 'త్వరిత చర్యలు',
    'admin.createElection': 'కొత్త ఎన్నిక సృష్టించండి',
    'admin.manageVoters': 'ఓటర్లను నిర్వహించండి',
    'admin.viewAnalytics': 'విశ్లేషణలను చూడండి',
    'admin.activeElections': 'క్రియాశీల ఎన్నికలు',
    'admin.noElections': 'క్రియాశీల ఎన్నికలు లేవు. ప్రారంభించడానికి ఒకటి సృష్టించండి.',
    'admin.edit': 'సవరించండి',
    'admin.end': 'ముగించండి',
    'admin.accessDenied': 'యాక్సెస్ నిరాకరించబడింది',
    'admin.connectWalletMessage': 'అడ్మిన్ ప్యానెల్‌ను యాక్సెస్ చేయడానికి దయచేసి మీ వాలెట్‌ను కనెక్ట్ చేయండి.',
    'admin.unauthorized': 'అనధికార యాక్సెస్',
    'admin.noPrivileges': 'ఈ ప్యానెల్‌ను యాక్సెస్ చేయడానికి మీకు అడ్మినిస్ట్రేటర్ అధికారాలు లేవు.',
    
    // Create Election Modal
    'createElection.title': 'కొత్త ఎన్నిక సృష్టించండి',
    'createElection.electionTitle': 'ఎన్నిక శీర్షిక',
    'createElection.description': 'వివరణ',
    'createElection.startTime': 'ప్రారంభ సమయం',
    'createElection.endTime': 'ముగింపు సమయం',
    'createElection.candidates': 'అభ్యర్థులు',
    'createElection.addCandidate': 'అభ్యర్థిని జోడించండి',
    'createElection.candidateName': 'అభ్యర్థి పేరు',
    'createElection.party': 'పార్టీ',
    'createElection.candidateDescription': 'వివరణ',
    'createElection.create': 'ఎన్నిక సృష్టించండి',
    'createElection.cancel': 'రద్దు చేయండి',
    
    // Chatbot
    'chatbot.title': 'డివోట్ సహాయకుడు',
    'chatbot.greeting': 'నమస్కారం! నేను మీ డివోట్ సహాయకుడిని. ఈరోజు ఓటింగ్‌లో నేను మీకు ఎలా సహాయం చేయగలను?',
    'chatbot.placeholder': 'మీ సందేశాన్ని టైప్ చేయండి...',
    'chatbot.languageChanged': 'భాష తెలుగుకు మార్చబడింది. డివోట్ తో నేను మీకు ఎలా సహాయం చేయగలను?',
    'chatbot.errorMessage': 'క్షమించండి, AI సేవతో కనెక్ట్ చేయడంలో సమస్య ఉంది. Ollama deepseek-r1 మోడల్‌తో రన్ అవుతుందని నిర్ధారించుకోండి.',
    'chatbot.stopSpeaking': 'మాట్లాడడం ఆపండి',
    'chatbot.readAloud': 'బిగ్గరగా చదవండి',
    
    // Common
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'లోపం',
    'common.success': 'విజయం',
    'common.cancel': 'రద్దు చేయండి',
    'common.confirm': 'ధృవీకరించండి',
    'common.close': 'మూసివేయండి',
    'common.save': 'సేవ్ చేయండి',
    'common.delete': 'తొలగించండి',
    'common.edit': 'సవరించండి',
    'common.view': 'చూడండి',
    'common.required': 'అవసరం',
    'common.optional': 'ఐచ్ఛికం',
    'common.yes': 'అవును',
    'common.no': 'లేదు',
  },
  
  mr: {
    // Header
    'header.title': 'डीव्होट',
    'header.subtitle': 'विकेंद्रीकृत मतदान प्रणाली',
    'header.dashboard': 'डॅशबोर्ड',
    'header.register': 'नोंदणी',
    'header.vote': 'मतदान',
    'header.results': 'निकाल',
    'header.audit': 'ऑडिट ट्रेल',
    'header.admin': 'अॅडमिन',
    'header.aiSetup': 'AI सेटअप',
    'header.connectWallet': 'MetaMask जोडा',
    'header.disconnect': 'डिस्कनेक्ट',
    
    // Dashboard
    'dashboard.welcome': 'डीव्होटमध्ये आपले स्वागत आहे',
    'dashboard.description': 'ब्लॉकचेन तंत्रज्ञानाद्वारे चालवलेले भारताचे पहिले विकेंद्रीकृत मतदान प्लॅटफॉर्म. लोकशाही भविष्यासाठी पारदर्शक, सुरक्षित आणि सत्यापन करण्यायोग्य निवडणुका सुनिश्चित करते.',
    'dashboard.connectWallet': 'मतदानात सहभागी होण्यासाठी आपले MetaMask वॉलेट जोडा',
    'dashboard.totalVoters': 'एकूण मतदार',
    'dashboard.votesCast': 'दिलेली मते',
    'dashboard.activeElections': 'सक्रिय निवडणुका',
    'dashboard.turnoutRate': 'मतदान दर',
    'dashboard.registerToVote': 'मतदानासाठी नोंदणी करा',
    'dashboard.castVote': 'आपले मत द्या',
    'dashboard.viewResults': 'निकाल पहा',
    'dashboard.auditTrail': 'ऑडिट ट्रेल',
    'dashboard.secureTransparent': 'सुरक्षित आणि पारदर्शक',
    'dashboard.secureDescription': 'ब्लॉकचेन-आधारित मतदान संपूर्ण पारदर्शकतेसह छेडछाड-प्रतिरोधी निवडणुका सुनिश्चित करते.',
    'dashboard.onePersonOneVote': 'एक व्यक्ती, एक मत',
    'dashboard.onePersonDescription': 'MetaMask एकीकरण सुनिश्चित करते की प्रत्येक वॉलेट प्रति निवडणूक फक्त एकदाच मत देऊ शकते.',
    'dashboard.realTimeResults': 'रिअल-टाइम निकाल',
    'dashboard.realTimeDescription': 'मते दिली जातात तेव्हा थेट मतदान निकाल आणि सर्वसमावेशक विश्लेषण पहा.',
    'dashboard.auditTrailFeature': 'ऑडिट ट्रेल',
    'dashboard.auditDescription': 'सर्व मतदान क्रियाकलापांसाठी संपूर्ण व्यवहार इतिहास आणि सत्यापन.',
    'dashboard.voteNow': 'आता मत द्या',
    
    // Voter Registration
    'registration.title': 'मतदार नोंदणी',
    'registration.subtitle': 'विकेंद्रीकृत मतदानात सहभागी होण्यासाठी नोंदणी करा',
    'registration.secureRegistration': 'सुरक्षित नोंदणी',
    'registration.securityNotice': 'आपली नोंदणी ब्लॉकचेनवर रेकॉर्ड केली जाईल आणि आपल्या वॉलेट पत्त्याशी जोडली जाईल. हे गोपनीयता आणि सुरक्षा राखून एक व्यक्ती, एक मत सुनिश्चित करते.',
    'registration.fullName': 'पूर्ण नाव',
    'registration.email': 'ईमेल पत्ता',
    'registration.phone': 'फोन नंबर',
    'registration.aadhaar': 'आधार नंबर',
    'registration.address': 'पत्ता',
    'registration.connectedWallet': 'जोडलेले वॉलेट',
    'registration.walletNotice': 'आपली नोंदणी याच्याशी जोडली जाईल:',
    'registration.terms': 'नोंदणी करून, आपण सहमत आहात की आपली माहिती मतदान सत्यापन हेतूंसाठी ब्लॉकचेनवर संग्रहित केली जाईल. ही नोंदणी कायमची आहे आणि सुधारली जाऊ शकत नाही.',
    'registration.register': 'मतदार म्हणून नोंदणी करा',
    'registration.registering': 'नोंदणी करत आहे...',
    'registration.success': 'नोंदणी यशस्वी!',
    'registration.successMessage': 'आपण ब्लॉकचेनवर मतदार म्हणून यशस्वीरित्या नोंदणी केली आहे.',
    'registration.alreadyRegistered': 'आधीच नोंदणी केली आहे',
    'registration.alreadyMessage': 'आपण या वॉलेट पत्त्यासह आधीच मतदार म्हणून नोंदणी केली आहे.',
    'registration.walletNotConnected': 'वॉलेट जोडलेले नाही',
    'registration.connectMessage': 'मतदार म्हणून नोंदणी करण्यासाठी कृपया आपले MetaMask वॉलेट जोडा.',
    'registration.goToVoting': 'मतदान बूथवर जा',
    
    // Voting Booth
    'voting.title': 'मतदान बूथ',
    'voting.subtitle': 'ब्लॉकचेनवर सुरक्षितपणे आपले मत द्या',
    'voting.selectElection': 'निवडणूक निवडा',
    'voting.selectCandidate': 'उमेदवार निवडा',
    'voting.confirmVote': 'आपल्या मताची पुष्टी करा',
    'voting.election': 'निवडणूक:',
    'voting.selectedCandidate': 'निवडलेला उमेदवार:',
    'voting.important': 'महत्त्वाचे:',
    'voting.permanentWarning': 'एकदा आपले मत दिल्यानंतर, ते बदलले जाऊ शकत नाही. आपले मत ब्लॉकचेनवर रेकॉर्ड केले जाईल आणि ते कायमचे आहे.',
    'voting.castVote': 'मत द्या',
    'voting.castingVote': 'मत देत आहे...',
    'voting.voteConfirmed': 'मताची पुष्टी झाली!',
    'voting.confirmMessage': 'आपले मत ब्लॉकचेनवर यशस्वीरित्या रेकॉर्ड केले गेले आहे.',
    'voting.voteAnother': 'दुसऱ्या निवडणुकीत मत द्या',
    'voting.alreadyVoted': 'आधीच मत दिले आहे',
    'voting.noActiveElections': 'सक्रिय निवडणुका नाहीत',
    'voting.noElectionsMessage': 'सध्या मतदानासाठी सक्रिय निवडणुका उपलब्ध नाहीत.',
    
    // Results
    'results.title': 'निवडणूक निकाल',
    'results.subtitle': 'ब्लॉकचेनद्वारे चालवलेले रिअल-टाइम मतदान निकाल',
    'results.selectElection': 'निवडणूक निवडा',
    'results.totalVotes': 'एकूण मते',
    'results.turnout': 'मतदान',
    'results.leading': 'आघाडीवर',
    'results.voteDistribution': 'मत वितरण',
    'results.liveUpdates': 'थेट अपडेट्स',
    'results.liveMessage': 'मते दिली जातात आणि ब्लॉकचेनवर पुष्टी केली जाते तेव्हा निकाल रिअल-टाइममध्ये अपडेट केले जातात. सर्व मत मोजणी ऑडिट ट्रेलद्वारे सत्यापन करण्यायोग्य आहे.',
    'results.noElections': 'निवडणुका उपलब्ध नाहीत',
    'results.noElectionsMessage': 'सध्या निकाल दाखवण्यासाठी निवडणुका नाहीत.',
    
    // Audit Trail
    'audit.title': 'ऑडिट ट्रेल',
    'audit.subtitle': 'ब्लॉकचेन सत्यापनाद्वारे संपूर्ण पारदर्शकता',
    'audit.search': 'व्यवहार हॅश किंवा मतदार पत्त्याद्वारे शोधा...',
    'audit.allTransactions': 'सर्व व्यवहार',
    'audit.votes': 'मते',
    'audit.registrations': 'नोंदणी',
    'audit.elections': 'निवडणुका',
    'audit.totalTransactions': 'एकूण व्यवहार',
    'audit.votesCast': 'दिलेली मते',
    'audit.gasUsed': 'वापरलेला गॅस',
    'audit.transactionHistory': 'व्यवहार इतिहास',
    'audit.transactionHash': 'व्यवहार हॅश',
    'audit.type': 'प्रकार',
    'audit.voterAddress': 'मतदार पत्ता',
    'audit.timestamp': 'टाइमस्टॅम्प',
    'audit.status': 'स्थिती',
    'audit.confirmed': 'पुष्टी केली',
    'audit.noTransactions': 'आपल्या निकषांशी जुळणारे व्यवहार सापडले नाहीत.',
    
    // Admin Panel
    'admin.title': 'अॅडमिन पॅनेल',
    'admin.subtitle': 'निवडणुकांचे व्यवस्थापन करा आणि सिस्टम कार्यप्रदर्शनाचे निरीक्षण करा',
    'admin.totalElections': 'एकूण निवडणुका',
    'admin.registeredVoters': 'नोंदणीकृत मतदार',
    'admin.systemStatus': 'सिस्टम स्थिती',
    'admin.active': 'सक्रिय',
    'admin.quickActions': 'त्वरित कृती',
    'admin.createElection': 'नवीन निवडणूक तयार करा',
    'admin.manageVoters': 'मतदारांचे व्यवस्थापन करा',
    'admin.viewAnalytics': 'विश्लेषण पहा',
    'admin.activeElections': 'सक्रिय निवडणुका',
    'admin.noElections': 'सक्रिय निवडणुका नाहीत. सुरुवात करण्यासाठी एक तयार करा.',
    'admin.edit': 'संपादित करा',
    'admin.end': 'समाप्त करा',
    'admin.accessDenied': 'प्रवेश नाकारला',
    'admin.connectWalletMessage': 'अॅडमिन पॅनेलमध्ये प्रवेश करण्यासाठी कृपया आपले वॉलेट जोडा.',
    'admin.unauthorized': 'अनधिकृत प्रवेश',
    'admin.noPrivileges': 'या पॅनेलमध्ये प्रवेश करण्यासाठी आपल्याकडे प्रशासक विशेषाधिकार नाहीत.',
    
    // Create Election Modal
    'createElection.title': 'नवीन निवडणूक तयार करा',
    'createElection.electionTitle': 'निवडणूक शीर्षक',
    'createElection.description': 'वर्णन',
    'createElection.startTime': 'सुरुवातीची वेळ',
    'createElection.endTime': 'समाप्तीची वेळ',
    'createElection.candidates': 'उमेदवार',
    'createElection.addCandidate': 'उमेदवार जोडा',
    'createElection.candidateName': 'उमेदवाराचे नाव',
    'createElection.party': 'पक्ष',
    'createElection.candidateDescription': 'वर्णन',
    'createElection.create': 'निवडणूक तयार करा',
    'createElection.cancel': 'रद्द करा',
    
    // Chatbot
    'chatbot.title': 'डीव्होट सहाय्यक',
    'chatbot.greeting': 'नमस्कार! मी तुमचा डीव्होट सहाय्यक आहे. आज मतदानात मी तुम्हाला कशी मदत करू शकतो?',
    'chatbot.placeholder': 'तुमचा संदेश टाइप करा...',
    'chatbot.languageChanged': 'भाषा मराठीत बदलली आहे. डीव्होट सह मी तुम्हाला कशी मदत करू शकतो?',
    'chatbot.errorMessage': 'माफ करा, AI सेवेशी जोडण्यात अडचण येत आहे. Ollama deepseek-r1 मॉडेलसह चालत आहे याची खात्री करा.',
    'chatbot.stopSpeaking': 'बोलणे थांबवा',
    'chatbot.readAloud': 'मोठ्याने वाचा',
    
    // Common
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.success': 'यश',
    'common.cancel': 'रद्द करा',
    'common.confirm': 'पुष्टी करा',
    'common.close': 'बंद करा',
    'common.save': 'जतन करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.view': 'पहा',
    'common.required': 'आवश्यक',
    'common.optional': 'पर्यायी',
    'common.yes': 'होय',
    'common.no': 'नाही',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('dvote-language');
    if (savedLanguage && supportedLanguages.find(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (language: string) => {
    setCurrentLanguage(language);
    localStorage.setItem('dvote-language', language);
    
    // Update document language and direction
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const isRTL = currentLanguage === 'ar';

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        supportedLanguages,
        t,
        isRTL,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};